version: '3.8'
services:
  database:
    build:
      context: ./services/database
    image: mpaa_postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: kubernetes_project
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
  api:
    build:
      context: ./services/api
    image: kubernetes_project_api_v5.2
    ports:
      - "3000:3000"
    environment:
      DB_USER: admin
      DB_PASSWORD: admin123
      DB_HOST: database
      DB_NAME: kubernetes_project
      DB_PORT: 5432
    depends_on:
      - database
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - xpack.security.http.ssl.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - backend
  kibana:
    build: 
      context: ./services/kibana
    image: mpaa_kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - backend
networks:
  backend:
    driver: bridge