version: '3.8'
services:
  database:
    build:
      context: ./services/database
    image: kubernetes_project_database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: kubernetes_project
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
  api:
    build:
      context: ./services/api
    image: kubernetes_project_api
    ports:
      - "3000:3000"
    environment:
      DB_USER: admin
      DB_PASSWORD: admin123
      DB_HOST: database
      DB_NAME: kubernetes_project
      DB_PORT: 5432
    depends_on:
      - database
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"