apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: kubernetes_project_api
          env:
            - name: DB_USER
              value: "admin"
            - name: DB_PASSWORD
              value: "admin123"
            - name: DB_HOST
              value: "database"
            - name: DB_NAME
              value: "kubernetes_project"
            - name: DB_PORT
              value: "5432"
          ports:
            - containerPort: 3000
