apiVersion: apps/v1
kind: Deployment
metadata:
  name: vvn-project
  namespace: mpaa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vvn-project
  template:
    metadata:
      labels:
        app: vvn-project
    spec:
      containers:
      - name: database
        image: registry.gitlab.com/bp-sojka/mppa/vvn_postgresql:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "kubernetes_project"
        - name: POSTGRES_USER
          value: "admin"
        - name: POSTGRES_PASSWORD
          value: "admin123"
      - name: api
        image: registry.gitlab.com/bp-sojka/mppa/vvn_api
        ports:
        - containerPort: 3000
        env:
        - name: DB_USER
          value: "admin"
        - name: DB_PASSWORD
          value: "admin123"
        - name: DB_HOST
          value: "localhost"
        - name: DB_NAME
          value: "kubernetes_project"
        - name: DB_PORT
          value: "5432"
      - name: elasticsearch
        image: registry.gitlab.com/bp-sojka/mppa/vvn_elasticsearch
        ports:
        - containerPort: 9200
        - containerPort: 9300
        env:
        - name: discovery.type
          value: "single-node"
        - name: ES_JAVA_OPTS
          value: "-Xms512m -Xmx512m"
        resources:
          requests:
            memory: "512Mi"
            cpu: "0.5"
          limits:
            memory: "2Gi"
            cpu: "1"
      - name: kibana
        image: registry.gitlab.com/bp-sojka/mppa/vvn_kibana
        ports:
        - containerPort: 5601
        env:
        - name: ELASTICSEARCH_URL
          value: "http://localhost:9200"
---
apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: mpaa
spec:
  selector:
    app: vvn-project
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: mpaa
spec:
  selector:
    app: vvn-project
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: mpaa
spec:
  selector:
    app: vvn-project
  ports:
  - protocol: TCP
    port: 9200
    targetPort: 9200
    name: http
  - protocol: TCP
    port: 9300
    targetPort: 9300
    name: transport
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: mpaa
spec:
  selector:
    app: vvn-project
  ports:
  - protocol: TCP
    port: 5601
    targetPort: 5601
  type: ClusterIP
